04 lection2
js-tasks-ru/htmlcss-20211021_darak-ltd pull request #5
Opened 2021-11-02 09:52 UTC by Michael2M-dot

ПР с элементами гистограмма и селетон

2021-11-02 09:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-03 20:24 UTC, GSemikozov requested changes

2021-11-03 20:24 UTC, GSemikozov commented on 04-lection2/01-histogram/container.css
> +    margin: 0 auto;
не хватает еще ax-width: 1110px

2021-11-03 20:24 UTC, GSemikozov commented on 04-lection2/01-histogram/container.css
> +.container__histogram {
под каждый компонент свой модификатор контейнера будет очен не универсальным решением)
если нужен такой враппер чисто для решения задачи - то можно в соответствующем хтмл через тег  style оформить соответствующий стиль

2021-11-03 20:24 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex: auto;
можно еще указать flex-basis: 9px чтобы в большей степени соответствовать макету

2021-11-04 00:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-04 00:04 UTC, Michael2M-dot commented on 04-lection2/01-histogram/histogram.css
> +    flex: auto;
Исправил комбинированное свойство flex:, добавил gap.

2021-11-04 00:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-04 00:10 UTC, Michael2M-dot commented on 04-lection2/01-histogram/container.css
> +.container__histogram {
вынес в тег style,  я правильно понял или нужно подкорректировать

2021-11-04 00:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-04 00:13 UTC, Michael2M-dot commented on 04-lection2/01-histogram/container.css
> +    margin: 0 auto;
Не совсем понял для чего ширину сделать. Это же вроде не итоговая верстка а компонент

2021-11-04 00:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-04 01:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-04 19:58 UTC, GSemikozov requested changes

2021-11-04 19:58 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
здесь и ниже ширины для линий лучше записать в процентах

2021-11-04 22:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-04 22:25 UTC, Michael2M-dot commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
Да, отличное решение с процентами))) Теперь при масштабировании не будет проблем с размером полей

2021-11-05 14:58 UTC, GSemikozov approved these changes

2021-11-05 14:58 UTC, merged