06 lection4
js-tasks-ru/htmlcss-20211021_darak-ltd pull request #8
Opened 2021-11-18 08:39 UTC by Michael2M-dot

итоги по 4-ой лекции

2021-11-18 08:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-18 11:43 UTC, GSemikozov requested changes

2021-11-18 11:43 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    background-image: url("./public/avatar-200.jpg");
картинка аватара обычно вставляется пользователем, а потом подгружается с сервера - в этом случае вставка аватара фоном в отдельном файле стилей не будет работать. Предлагаю переписать на <img>

2021-11-18 11:43 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar__container {
это блок, .avatar, и все верно - именно здесь мы задаем фиксированные размеры для аватара + border-radius: 50%; overflow: hidden;

2021-11-18 11:43 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    width: 102px;
width + height 100%

2021-11-20 03:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-20 03:43 UTC, Michael2M-dot commented on 06-lection4/01-avatar/avatar.css
> +    background-image: url("./public/avatar-200.jpg");
Понял. Подправил

2021-11-20 03:43 UTC, Michael2M-dot commented on 06-lection4/01-avatar/avatar.css
> +.avatar__container {
да, уразумел

2021-11-20 04:01 UTC, Michael2M-dot commented on 06-lection4/01-avatar/avatar.css
> +    width: 102px;
исправил

2021-11-21 12:56 UTC, GSemikozov approved these changes

2021-11-21 12:56 UTC, merged